// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectedMessage() string {
	foo := provideFoo()
	string2 := getS(foo)
	return string2
}
