// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wrie.go:

func injectedMessage() string {
	foo := provideFoo()
	string2 := foo.S
	return string2
}
