// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(name string) Mission {
	player := NewPlayer(name)
	monster := NewMonster()
	mission := NewMission(player, monster)
	return mission
}

func InitEndingA(name string) EndingA {
	player := NewPlayer(name)
	monster := NewMonster()
	endingA := NewEndingA(player, monster)
	return endingA
}

func InitEndingB(name string) EndingB {
	player := NewPlayer(name)
	monster := NewMonster()
	endingB := NewEndingB(player, monster)
	return endingB
}
